# Generated by Django 4.2.2 on 2023-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=35)),
                ('actress', models.CharField(max_length=35)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
